apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sod7el5e5-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:000622898c52021cd0f60bf8fd6c618a16a05991@sha256:3e4374fcc1da0e57bb2767804cb551959dabebcef2750bdcc50d5963cfdf5d65
          name: container-image
